// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectMTG.DataAccess;

namespace ProjectMTG.DataAccess.Migrations
{
    [DbContext(typeof(CollectionContext))]
    partial class CollectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectMTG.Model.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("artist");

                    b.Property<string>("colors");

                    b.Property<float>("convertedManaCost");

                    b.Property<string>("loyalty");

                    b.Property<string>("manaCost");

                    b.Property<int>("multiverseId");

                    b.Property<string>("name");

                    b.Property<string>("number");

                    b.Property<string>("power");

                    b.Property<string>("rarity");

                    b.Property<string>("scryfallId");

                    b.Property<string>("scryfallIllustrationId");

                    b.Property<string>("scryfallOracleId");

                    b.Property<string>("subtype");

                    b.Property<string>("supertype");

                    b.Property<int>("tcgplayerProductId");

                    b.Property<string>("tcgplayerPurchaseUrl");

                    b.Property<string>("text");

                    b.Property<string>("toughness");

                    b.Property<string>("type");

                    b.Property<string>("types");

                    b.Property<string>("uuid");

                    b.Property<string>("uuidV421");

                    b.HasKey("CardId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("ProjectMTG.Model.Deck", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeckName");

                    b.Property<int>("UserId");

                    b.HasKey("DeckId");

                    b.HasIndex("UserId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("ProjectMTG.Model.DeckCards", b =>
                {
                    b.Property<int>("DeckCardId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeckId");

                    b.Property<string>("artist");

                    b.Property<string>("colors");

                    b.Property<float>("convertedManaCost");

                    b.Property<string>("loyalty");

                    b.Property<string>("manaCost");

                    b.Property<int>("multiverseId");

                    b.Property<string>("name");

                    b.Property<string>("number");

                    b.Property<string>("power");

                    b.Property<string>("rarity");

                    b.Property<string>("scryfallId");

                    b.Property<string>("scryfallIllustrationId");

                    b.Property<string>("scryfallOracleId");

                    b.Property<string>("subtype");

                    b.Property<string>("supertype");

                    b.Property<int>("tcgplayerProductId");

                    b.Property<string>("tcgplayerPurchaseUrl");

                    b.Property<string>("text");

                    b.Property<string>("toughness");

                    b.Property<string>("type");

                    b.Property<string>("types");

                    b.Property<string>("uuid");

                    b.Property<string>("uuidV421");

                    b.HasKey("DeckCardId");

                    b.HasIndex("DeckId");

                    b.ToTable("DeckCard");
                });

            modelBuilder.Entity("ProjectMTG.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectMTG.Model.Deck", b =>
                {
                    b.HasOne("ProjectMTG.Model.User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProjectMTG.Model.DeckCards", b =>
                {
                    b.HasOne("ProjectMTG.Model.Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
